version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      version: '3'
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/oce/Transcend/docker/