version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - type: bind
        source: ./dbdata
        target: /var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      version: '3'
    volumes:
      - type: bind
        source: ./dbdata
        target: /var/lib/mysql
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./dbdata
        target: /var/lib/mysql
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oce/GitHub/gitM1/dbdata