-- MySQL Script generated by MySQL Workbench
-- ven. 16 févr. 2024 10:18:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e21901204_db2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e21901204_db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e21901204_db2` DEFAULT CHARACTER SET utf8 ;
USE `e21901204_db2` ;

-- -----------------------------------------------------
-- Table `e21901204_db2`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e21901204_db2`.`lieu` ;

CREATE TABLE IF NOT EXISTS `e21901204_db2`.`lieu` (
                                                      `id_lieu` INT NOT NULL AUTO_INCREMENT,
                                                      `nom_lieu` VARCHAR(100) NOT NULL,
    `adresse_lieu` VARCHAR(100) NOT NULL,
    `capacite_lieu` INT NOT NULL,
    PRIMARY KEY (`id_lieu`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21901204_db2`.`evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e21901204_db2`.`evenement` ;

CREATE TABLE IF NOT EXISTS `e21901204_db2`.`evenement` (
                                                           `id_evenement` INT NOT NULL AUTO_INCREMENT,
                                                           `nom_evenement` VARCHAR(100) NOT NULL,
    `duree_evenement` INT NOT NULL,
    `nb_max_evenement` INT NOT NULL,
    `date_evenement` DATE NOT NULL,
    `id_lieu` INT NOT NULL,
    `desc_evenement` TEXT NOT NULL,
    `image_evenement` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id_evenement`),
    INDEX `fk_evenement_1_idx` (`id_lieu` ASC) VISIBLE,
    CONSTRAINT `fk_evenement_1`
    FOREIGN KEY (`id_lieu`)
    REFERENCES `e21901204_db2`.`lieu` (`id_lieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21901204_db2`.`membre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e21901204_db2`.`membre` ;

CREATE TABLE IF NOT EXISTS `e21901204_db2`.`membre` (
                                                        `id_membre` INT NOT NULL AUTO_INCREMENT,
                                                        `email_membre` VARCHAR(100) NOT NULL,
    `nom_membre` VARCHAR(100) NOT NULL,
    `prenom_membre` VARCHAR(100) NOT NULL,
    `role_membre` VARCHAR(100) NOT NULL,
    `adresse_membre` VARCHAR(100) NOT NULL,
    `photo_membre` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id_membre`),
    UNIQUE INDEX `email_membre_UNIQUE` (`email_membre` ASC) VISIBLE)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `e21901204_db2`.`inscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e21901204_db2`.`inscription` ;

CREATE TABLE IF NOT EXISTS `e21901204_db2`.`inscription` (
                                                             `email_membre` VARCHAR(100) NOT NULL,
    `id_evenement` INT NOT NULL,
    INDEX `fk_inscription_1_idx` (`id_evenement` ASC) VISIBLE,
    INDEX `fk_inscription_2_idx` (`email_membre` ASC) VISIBLE,
    CONSTRAINT `fk_inscription_1`
    FOREIGN KEY (`id_evenement`)
    REFERENCES `e21901204_db2`.`evenement` (`id_evenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_inscription_2`
    FOREIGN KEY (`email_membre`)
    REFERENCES `e21901204_db2`.`membre` (`email_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `e21901204_db2`.`lieu`
-- -----------------------------------------------------
START TRANSACTION;
USE `e21901204_db2`;
INSERT INTO `e21901204_db2`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (1, 'Opera', 'Paris', 10000);
INSERT INTO `e21901204_db2`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (2, 'Quartz', 'Brest', 5000);
INSERT INTO `e21901204_db2`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (DEFAULT, 'Arena', 'Brest', 7000);
INSERT INTO `e21901204_db2`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (DEFAULT, '', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `e21901204_db2`.`evenement`
-- -----------------------------------------------------
START TRANSACTION;
USE `e21901204_db2`;
INSERT INTO `e21901204_db2`.`evenement` (`id_evenement`, `nom_evenement`, `duree_evenement`, `nb_max_evenement`, `date_evenement`, `id_lieu`) VALUES (1, 'Ballet', 2, 3000, '2023-12-01', 1);
INSERT INTO `e21901204_db2`.`evenement` (`id_evenement`, `nom_evenement`, `duree_evenement`, `nb_max_evenement`, `date_evenement`, `id_lieu`) VALUES (2, 'Le malade imaginaire', 3, 4000, '2024-12-01', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `e21901204_db2`.`membre`
-- -----------------------------------------------------



COMMIT;

