-- MySQL Script generated by MySQL Workbench
-- ven. 16 févr. 2024 10:18:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_db` DEFAULT CHARACTER SET utf8 ;
USE `app_db` ;

-- -----------------------------------------------------
-- Table `app_db`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_db`.`lieu` ;

CREATE TABLE IF NOT EXISTS `app_db`.`lieu` (
  `id_lieu` INT NOT NULL AUTO_INCREMENT,
  `nom_lieu` VARCHAR(100) NOT NULL,
  `adresse_lieu` VARCHAR(100) NOT NULL,
  `capacite_lieu` INT NOT NULL,
  PRIMARY KEY (`id_lieu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_db`.`evenement` ;

CREATE TABLE IF NOT EXISTS `app_db`.`evenement` (
  `id_evenement` INT NOT NULL AUTO_INCREMENT,
  `nom_evenement` VARCHAR(100) NOT NULL,
  `duree_evenement` INT NOT NULL,
  `nb_max_evenement` INT NOT NULL,
  `date_evenement` DATE NOT NULL,
  `id_lieu` INT NOT NULL,
  `desc_evenement` TEXT NOT NULL,
  `image_evenement` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_evenement`),
  INDEX `fk_evenement_1_idx` (`id_lieu` ASC) VISIBLE,
  CONSTRAINT `fk_evenement_1`
    FOREIGN KEY (`id_lieu`)
    REFERENCES `app_db`.`lieu` (`id_lieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`membre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_db`.`membre` ;

CREATE TABLE IF NOT EXISTS `app_db`.`membre` (
  `id_membre` INT NOT NULL AUTO_INCREMENT,
  `email_membre` VARCHAR(100) NOT NULL,
  `nom_membre` VARCHAR(100) NOT NULL,
  `prenom_membre` VARCHAR(100) NOT NULL,
  `role_membre` VARCHAR(100) NOT NULL,
  `adresse_membre` VARCHAR(100) NOT NULL,
  `photo_membre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_membre`),
  UNIQUE INDEX `email_membre_UNIQUE` (`email_membre` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_db`.`inscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_db`.`inscription` ;

CREATE TABLE IF NOT EXISTS `app_db`.`inscription` (
  `email_membre` VARCHAR(100) NOT NULL,
  `id_evenement` INT NOT NULL,
  INDEX `fk_inscription_1_idx` (`id_evenement` ASC) VISIBLE,
  INDEX `fk_inscription_2_idx` (`email_membre` ASC) VISIBLE,
  CONSTRAINT `fk_inscription_1`
    FOREIGN KEY (`id_evenement`)
    REFERENCES `app_db`.`evenement` (`id_evenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscription_2`
    FOREIGN KEY (`email_membre`)
    REFERENCES `app_db`.`membre` (`email_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `app_db`.`lieu`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_db`;
INSERT INTO `app_db`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (1, 'Opera', 'Paris', 10000);
INSERT INTO `app_db`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (2, 'Quartz', 'Brest', 5000);
INSERT INTO `app_db`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (DEFAULT, 'Arena', 'Brest', 7000);
INSERT INTO `app_db`.`lieu` (`id_lieu`, `nom_lieu`, `adresse_lieu`, `capacite_lieu`) VALUES (DEFAULT, '', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_db`.`evenement`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_db`;
INSERT INTO `app_db`.`evenement` (`id_evenement`, `nom_evenement`, `duree_evenement`, `nb_max_evenement`, `date_evenement`, `id_lieu`) VALUES (1, 'Ballet', 2, 3000, '2023-12-01', 1);
INSERT INTO `app_db`.`evenement` (`id_evenement`, `nom_evenement`, `duree_evenement`, `nb_max_evenement`, `date_evenement`, `id_lieu`) VALUES (2, 'Le malade imaginaire', 3, 4000, '2024-12-01', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_db`.`membre`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_db`;
INSERT INTO `app_db`.`membre` (`id_membre`, `email_membre`, `nom_membre`, `prenom_membre`, `age_membre`, `adresse_membre`) VALUES (1, 'oceane@gmail.com', 'pez', 'oce', 22, '4 rue Nap;29200 Brest');
INSERT INTO `app_db`.`membre` (`id_membre`, `email_membre`, `nom_membre`, `prenom_membre`, `age_membre`, `adresse_membre`) VALUES (DEFAULT, 'maxime@gmail.com', 'andre', 'max', 21, '12 rue test; 75000,Paris');

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_db`.`commentaire`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_db`;
INSERT INTO `app_db`.`commentaire` (`contenu_commentaire`, `id_evenement`, `email_membre`) VALUES ('Je me suis bien amusée !', 1, 'oceane@gmail.com');
INSERT INTO `app_db`.`commentaire` (`contenu_commentaire`, `id_evenement`, `email_membre`) VALUES ('c\'était bien', 2, 'maxime@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_db`.`inscription`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_db`;
INSERT INTO `app_db`.`inscription` (`email_membre`, `id_evenement`) VALUES ('oceane@gmail.com', 1);
INSERT INTO `app_db`.`inscription` (`email_membre`, `id_evenement`) VALUES ('maxime@gmail.com', 2);

COMMIT;

